# .github/workflows/actualizar.yml
name: Actualizar horarios

on:
  schedule:
    - cron: '*/30 * * * *'  # cada 30 minutos
  workflow_dispatch:       # también manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install pandas
      - name: Ejecutar script
        run: python procesar_gtfs.py
      - name: Subir cambios
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add horarios.json
          git commit -m "Actualiza horarios" || echo "Sin cambios"
          git push
